version: '3.9'
services:
    model:
        build:
            context: ./Model
        volumes: 
            -  ./Model:/app
    web:
        build: 
            context: ./DeployModel
        volumes:
            -  ./Model:/Model
            - ./DeployModel:/app
        ports:
           - "8000:8000"
        depends_on:
            - model